### ISSUE TITLE
Zynq harness not building on Zynq kokoro?

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#1049] opened 2019-09-12 00:29 UTC
Looking at the output of the latest Kokoro run for the Zynq.

https://console.cloud.google.com/storage/browser/symbiflow-prjxray/artifacts/prod/foss-fpga-tools/prjxray/continuous/database/zynq7/271/20190911-091600

If you look at the diff at https://storage.cloud.google.com/symbiflow-prjxray/artifacts/prod/foss-fpga-tools/prjxray/continuous/database/zynq7/271/20190911-091600/database/diff.html it doesn't look like the harness for zynq was actually built?

**Comment by tmichalak** [comment] 2019-09-12 06:37
@mithro Looks to me that it is caused by #1050. The PR with the fix is in #1051

**Comment by tmichalak** [comment] 2019-09-20 13:00
The PR has been merged and the issue is gone.

**Closed by tmichalak** 2019-09-20 13:00 UTC
